apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spiffe-vault.fullname" . }}
  labels:
    {{- include "spiffe-vault.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spiffe-vault.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spiffe-vault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh"]
          stdin: true
          tty: true
          {{- if .Values.docker.enabled }}
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: spire-agent-sockets
              mountPath: /var/run/spire/sockets
              readOnly: true
        {{- if .Values.docker.enabled }}
        - name: dind-daemon
          securityContext:
            {{- toYaml .Values.docker.securityContext | nindent 12 }}
          image: "{{ .Values.docker.image.repository }}:{{ .Values.docker.image.tag }}"
          imagePullPolicy: {{ .Values.docker.image.pullPolicy }}
          resources:
            {{- toYaml .Values.docker.resources | nindent 12 }}
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ''
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
        {{- end }}
      restartPolicy: OnFailure
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: spire-agent-sockets
          hostPath:
            path: /run/spire/agent-sockets
            type: DirectoryOrCreate
        {{- if .Values.docker.enabled }}
        - name: docker-graph-storage
          emptyDir: {}
        {{- end }}
