server:
  config:
    logLevel: debug
    jwtIssuer: spire-oidc.spire-system

  dataStorage:
    enabled: false

agent:
  config:
    logLevel: debug

oidc:
  enabled: true
  config:
    logLevel: debug

    domains:
      - localhost
      - oidc-spire.dev.localhost

    acme:
      tosAccepted: true
      emailAddress: my-email@domain.tld
      directoryUrl: https://acme-staging-v02.api.letsencrypt.org/directory

  service:
    type: ClusterIP

  insecureScheme:
    enabled: true

spire:
  clusterName: "dev-cluster"
  trustDomain: "dev.localhost"
